# Generated by Django 5.2.8 on 2025-11-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_codregistro_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codregistro',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
